name: find_lost_device1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flashlight: ^0.1.1
  intent: ^1.3.4
  android_intent: ^2.0.2
  google_sign_in: "^5.0.7"
  firebase_core: ^1.4.0
  firebase_auth: ^3.1.0
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^8.1.1+1
  http: ^0.13.3
  device_info: ^2.0.2
  firebase_database: ^7.1.1
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  geocoding: ^2.0.0
#  workmanager: ^0.2.0
  background_location: ^0.6.1
  flutter_background_location: ^0.0.4
#  flutter_isolate: ^2.0.0
  flutter_ringtone_player: ^3.0.0
  vibration: ^1.7.3
  maps_launcher: ^2.0.1
  sensors: ^2.0.3
  assets_audio_player: ^3.0.3+6
  battery_info: ^1.0.7
  fluttertoast: ^8.0.8
  in_app_review: ^2.0.2
  carousel_slider: ^4.0.0
  share: ^2.0.4
  permission_handler: ^8.1.4+2
  shared_value: ^2.1.0
  shared_preferences: ^2.0.7
  splashscreen: ^1.3.5

  #  flutter_sensors: ^0.1.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/sound_alarm.mp3
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
